language: android
env:
  - TEST_SUITE=units
  global:
    - ANDROID_TARGET=android-23
    - ANDROID_ABI=x86
android:
  components:
    - tools
    - platform-tools
    - build-tools-28
    - android-28
    - add-on
    - extra
licenses:
    - 'android-sdk-license-.+'
jdk:
    - oraclejdk8
script:
    - ./gradlew testAll
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
      - chmod +x ./gradlew
      - yes | sdkmanager "platforms;android-28"
      - yes | sdkmanager "build-tools;28.0.0"
      - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi x86 -no-accel
      - emulator -avd test -no-skin -no-audio -no-window &
      - android-wait-for-emulator
      - adb shell input keyevent 82 &
